### ISSUE TITLE
Grid Errors for small systems

### ISSUE THREAD

**Issue by niklundgren** [nanotheorygroup/kaldo#39] opened 2021-07-28 03:32 UTC
In certain cases, e.g. a replicated unitcell like 1x1xn, the detected_grid variable on line 34 in forceconstant.py behaves strangely.

We need a way to better control its behavior for some edge cases.

**Comment by gbarbalinardo** [comment] 2022-11-01 01:20
Closing since we weren't able to reproduce the issue.

**Closed by gbarbalinardo** 2022-11-01 01:20 UTC
